### PR TITLE
AddCloudFoundryIdentityCertificate improvements

### LINKED ISSUE #702: Calling AddCloudFoundryIdentityCertificate causes service container to be built
## Describe the bug
Calling AddCloudFoundryIdentityCertificate on ApplicationBuilder causes a service container to be built.
https://github.com/SteeltoeOSS/Steeltoe/blob/fc5ebe963718ef922c32fad6895adb38ef5975af/src/Security/src/Authentication.CloudFoundryCore/AuthenticationBuilderExtensions.cs#L280

## Expected behavior
Avoid premature container creation during its building stage. Resolution of the logger should done from the container by adding a `Configure` call for `MutualTlsAuthenticationOptions` outside of AddMutualTls call (as it's just a shorthand way to register options with values known at the container registration phase).

### PR DESCRIPTION
**Pull request by TimHess**
Add some missing overloads for #703
Remove usage of temporary service container #702 
Also removes IConfiguration param that we can work without
Fix for relevant piece of #667

### CODE REVIEW

**Review by dtillman — APPROVED** [review]
LGTM

File: src/Security/src/Authentication.CloudFoundryCore/MutualTlsAuthenticationOptionsPostConfigurer.cs [hunk 1]
```diff
@@ -2,24 +2,50 @@
...
 
         public void PostConfigure(string name, MutualTlsAuthenticationOptions options)
         {
             options.IssuerChain = _containerIdentityOptions.CurrentValue.IssuerChain;
+            options.Events = new CertificateAuthenticationEvents()
+            {
+                OnCertificateValidated = context =>
+                {
+                    var claims = new List<Claim>(context.Principal.Claims);
+                    if (CloudFoundryInstanceCertificate.TryParse(context.ClientCertificate, out var cfCert, _logger))
```
Comment (hananiel) [inline src/Security/src/Authentication.CloudFoundryCore/MutualTlsAuthenticationOptionsPostConfigurer.cs:35]: Tim, I did not see a test, but in running this did you see the log message showing up? I don't see why the logger wouldn't get resolved by the container, but just making sure.

**Review by hananiel — APPROVED** [review]

File: src/Security/src/Authentication.CloudFoundryCore/MutualTlsAuthenticationOptionsPostConfigurer.cs (hunk 1 above)
Comment (TimHess) [reply src/Security/src/Authentication.CloudFoundryCore/MutualTlsAuthenticationOptionsPostConfigurer.cs:35]: Yes, the log message does show up if there is a logger and cert validation fails
