### PR TITLE
Align Cloud Controller response handling with Spring, improve tests

### LINKED ISSUE #1446: Is the 503 status code correct when the request to check permissions in CF fails
Follow-up from https://github.com/SteeltoeOSS/Steeltoe/pull/1444/files#r1920383965 - double check what Spring Boot does

### PR DESCRIPTION
**Pull request by TimHess**
## Description

To answer the original question: when using Spring Boot as the spec for these interactions, HTTP 503 can be the "correct" response.

This PR:
- Adds testing of various potential cloud controller responses
- Allows usage of 401 response code (all 4xx errors besides 403) | [relevant Spring code](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/cloudfoundry/reactive/ReactiveCloudFoundrySecurityService.java#L103)
- Allows usage of 500 response code, with error message in response | [relevant Spring code](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/cloudfoundry/reactive/CloudFoundrySecurityInterceptor.java#L95)

Resolves #1446 

## Quality checklist

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [x] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [x] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

File: src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs [hunk 1]
```diff
@@ -75,23 +75,34 @@ public async Task<SecurityResult> GetPermissionsAsync(string accessToken, Cancel
...
         catch (Exception exception) when (!exception.IsCancellation())
         {
             _logger.LogError(exception, "Cloud Foundry returned exception while obtaining permissions from: {PermissionsUri}", checkPermissionsUri);
 
+            return new SecurityResult(HttpStatusCode.InternalServerError, exception.Message);
+        }
+        catch (Exception exception)
+        {
+            _logger.LogInformation(exception, "Task cancelled or timed out while obtaining permissions from: {PermissionsUri}", checkPermissionsUri);
+
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs:100]: This catch-all should be removed, so that the cancellation bubbles up and terminates the entire pipeline.

While it's useful to log a timeout, a client walking away because they closed their browser, or a consuming machine that restarts, should not pollute log files, as this is normal and expected behavior.

I would expect a true timeout while connecting to the auth server to bubble up and be caught and logged by ASP.NET itself, similar to any other exception type.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs [hunk 2]
```diff
@@ -365,6 +365,72 @@ public async Task Redacts_HTTP_headers()
...
+    [InlineData("forbidden", HttpStatusCode.Forbidden, PermissionsProvider.AccessDeniedMessage, "true")]
+    [InlineData("forbidden", HttpStatusCode.Forbidden, PermissionsProvider.AccessDeniedMessage, "false")]
+    [InlineData("timeout", HttpStatusCode.ServiceUnavailable, PermissionsProvider.CloudfoundryNotReachableMessage, "true")]
+    [InlineData("timeout", HttpStatusCode.OK, PermissionsProvider.CloudfoundryNotReachableMessage, "false")]
+    [InlineData("exception", HttpStatusCode.InternalServerError, @"Exception of type \u0027System.Net.Http.HttpRequestException\u0027 was thrown.", "true")]
+    [InlineData("exception", HttpStatusCode.OK, @"Exception of type \u0027System.Net.Http.HttpRequestException\u0027 was thrown.", "false")]
+    [InlineData("no_sensitive_data", HttpStatusCode.OK, null, "true")]
+    [InlineData("success", HttpStatusCode.OK, null, "true")]
+    [Theory]
+    public async Task CloudControllerScenarioTesting(string cloudControllerResponse, HttpStatusCode steeltoeStatusCode, string? errorMessage,
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs:383]: Please add an assertion on what's logged, similar to the first test [here](https://github.com/SteeltoeOSS/Steeltoe/blob/d306c94e067a4a6df4e3aa5135c84464e1518a76/src/Management/test/Endpoint.Test/Actuators/ThreadDump/EventPipeThreadDumperTest.cs#L26).

File: src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs [hunk 3]
```diff
@@ -19,16 +19,16 @@ namespace Steeltoe.Management.Endpoint.Actuators.CloudFoundry;
...
 {
-    private const string AuthorizationHeaderInvalid = "Authorization header is missing or invalid";
-    private const string CloudfoundryNotReachableMessage = "Cloud controller not reachable";
     private const string ReadSensitiveDataJsonPropertyName = "read_sensitive_data";
-    public const string HttpClientName = "CloudFoundrySecurity";
-    public const string ApplicationIdMissingMessage = "Application ID is not available";
-    public const string CloudfoundryApiMissingMessage = "Cloud controller URL is not available";
     public const string AccessDeniedMessage = "Access denied";
+    public const string ApplicationIdMissingMessage = "Application ID is not available";
     public const string AuthorizationHeaderName = "Authorization";
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs]: This constant can be removed. Callers can use `Microsoft.Net.Http.Headers.HeaderNames.Authorization`.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs [hunk 4]
```diff
@@ -19,16 +19,16 @@ namespace Steeltoe.Management.Endpoint.Actuators.CloudFoundry;
...
-    public const string BearerHeaderNamePrefix = "Bearer ";
-    private static readonly TimeSpan GetPermissionsTimeout = TimeSpan.FromMilliseconds(5000);
+    public const string AuthorizationHeaderInvalid = "Authorization header is missing or invalid";
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs]: Should be renamed to `AuthorizationHeaderInvalidMessage`.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs [hunk 5]
```diff
@@ -19,16 +19,16 @@ namespace Steeltoe.Management.Endpoint.Actuators.CloudFoundry;
...
+    public const string CloudfoundryApiMissingMessage = "Cloud controller URL is not available";
+    public const string CloudfoundryNotReachableMessage = "Cloud controller not reachable";
+    public const string HttpClientName = "CloudFoundrySecurity";
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs:23]: Please move this one above the list of messages.

Even better would be to introduce a nested static class `Messages` to keep them together. Then drop the "Message" suffix from the constant names.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs [hunk 6]
```diff
@@ -75,23 +75,35 @@ public async Task<SecurityResult> GetPermissionsAsync(string accessToken, Cancel
...
+
             _logger.LogError(exception, "Cloud Foundry returned exception while obtaining permissions from: {PermissionsUri}", checkPermissionsUri);
 
-            return new SecurityResult(HttpStatusCode.ServiceUnavailable, CloudfoundryNotReachableMessage);
+            return new SecurityResult(HttpStatusCode.InternalServerError, exception.Message);
         }
     }
 
-    public async Task<EndpointPermissions> GetPermissionsAsync(HttpResponseMessage response, CancellationToken cancellationToken)
+    public async Task<EndpointPermissions> ParsePermissionsAsync(HttpResponseMessage response, CancellationToken cancellationToken)
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs]: Consider renaming this to `ParsePermissionsResponseAsync`

File: src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs [hunk 7]
```diff
@@ -75,23 +75,35 @@ public async Task<SecurityResult> GetPermissionsAsync(string accessToken, Cancel
...
+            {
+                _logger.LogTrace(exception, "Task cancelled or timed out while obtaining permissions from: {PermissionsUri}", checkPermissionsUri);
+
+                throw;
+            }
+
             _logger.LogError(exception, "Cloud Foundry returned exception while obtaining permissions from: {PermissionsUri}", checkPermissionsUri);
 
-            return new SecurityResult(HttpStatusCode.ServiceUnavailable, CloudfoundryNotReachableMessage);
+            return new SecurityResult(HttpStatusCode.InternalServerError, exception.Message);
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs]: Would it be better to just let this throw? Then, depending on the environment, the exception stack trace is included or not.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs [hunk 8]
```diff
@@ -24,6 +24,25 @@ namespace Steeltoe.Management.Endpoint.Test.Actuators.CloudFoundry;
...
+    private const string CFForbiddenLog =
+        "INFO Steeltoe.Management.Endpoint.Actuators.CloudFoundry.PermissionsProvider: Cloud Foundry returned status: Forbidden while obtaining permissions from: https://example.api.com/v2/apps/forbidden/permissions";
+
+    private const string CFExceptionLog =
+        "FAIL Steeltoe.Management.Endpoint.Actuators.CloudFoundry.PermissionsProvider: Cloud Foundry returned exception while obtaining permissions from: https://example.api.com/v2/apps/exception/permissions";
+
+    private const string CFTimeoutLog =
+        "TRCE Steeltoe.Management.Endpoint.Actuators.CloudFoundry.PermissionsProvider: Task cancelled or timed out while obtaining permissions from: https://example.api.com/v2/apps/timeout/permissions";
+
+    private const string MiddlewareForbiddenLog =
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: Please use `typeof(T).FullName` instead of the explicit full type.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs [hunk 9]
```diff
@@ -365,6 +384,88 @@ public async Task Redacts_HTTP_headers()
...
+            if (!string.IsNullOrEmpty(errorMessage))
+            {
+                string errorText = await response.Content.ReadAsStringAsync(TestContext.Current.CancellationToken);
+                errorText.Should().Be($$"""{"security_error":"{{errorMessage}}"}""");
+            }
+            else
+            {
+                string responseBody = await response.Content.ReadAsStringAsync(TestContext.Current.CancellationToken);
+
+                responseBody.Should()
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: Please use `.BeJson()` and format into a readable raw string with line breaks.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs [hunk 10]
```diff
@@ -24,6 +24,25 @@ namespace Steeltoe.Management.Endpoint.Test.Actuators.CloudFoundry;
...
+    private const string MiddlewareForbiddenLog =
+        "FAIL Steeltoe.Management.Endpoint.Actuators.CloudFoundry.CloudFoundrySecurityMiddleware: Actuator Security Error: Forbidden - Access denied";
+
+    private const string MiddlewareUnauthorizedLog =
+        "FAIL Steeltoe.Management.Endpoint.Actuators.CloudFoundry.CloudFoundrySecurityMiddleware: Actuator Security Error: Unauthorized - Invalid token";
+
+    private const string MiddlewareUnavailableLog =
+        "FAIL Steeltoe.Management.Endpoint.Actuators.CloudFoundry.CloudFoundrySecurityMiddleware: Actuator Security Error: ServiceUnavailable - Cloud controller not reachable";
+
+    private const string CFExceptionMessage = @"Exception of type \u0027System.Net.Http.HttpRequestException\u0027 was thrown.";
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: Please replace the escape sequence with literal single quotes and use the following during assertion:
```c#
JsonValue.Create(errorMessage).ToJsonString()
```

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs [hunk 11]
```diff
@@ -24,6 +24,25 @@ namespace Steeltoe.Management.Endpoint.Test.Actuators.CloudFoundry;
 
 public sealed class CloudFoundrySecurityMiddlewareTest : BaseTest
 {
+    private const string CFForbiddenLog =
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: All logs here are related to CF, so I think these prefixes should be replaced with "Provider" or a similar term.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs [hunk 12]
```diff
@@ -365,6 +384,88 @@ public async Task Redacts_HTTP_headers()
...
+    [InlineData("forbidden", HttpStatusCode.Forbidden, PermissionsProvider.AccessDeniedMessage, CFForbiddenLog, "false")]
+    [InlineData("timeout", null, null, CFTimeoutLog, "true")]
+    [InlineData("timeout", null, null, CFTimeoutLog, "false")]
+    [InlineData("exception", HttpStatusCode.InternalServerError, CFExceptionMessage, CFExceptionLog, "true")]
+    [InlineData("exception", HttpStatusCode.OK, CFExceptionMessage, CFExceptionLog, "false")]
+    [InlineData("no_sensitive_data", HttpStatusCode.OK, null, MiddlewareForbiddenLog, "true")]
+    [InlineData("success", HttpStatusCode.OK, null, null, "true")]
+    [Theory]
+    public async Task CloudControllerScenarioTesting(string cloudControllerResponse, HttpStatusCode? steeltoeStatusCode, string? errorMessage,
+        string? expectedLogs, string useStatusCodeFromResponse)
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: `useStatusCodeFromResponse` should be `bool`

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/StartupWithSecurity.cs [hunk 13]
```diff
@@ -22,4 +25,15 @@ public void ConfigureServices(IServiceCollection services)
     public void Configure(IApplicationBuilder app)
     {
     }
+
+    private sealed class MockHttpClientFactory(MockHttpMessageHandler mockHttpMessageHandler) : IHttpClientFactory
+    {
+        private readonly MockHttpMessageHandler _mockHttpMessageHandler =
+            mockHttpMessageHandler ?? throw new ArgumentNullException(nameof(mockHttpMessageHandler));
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/StartupWithSecurity.cs]: Should use `ArgumentNullException.ThrowIfNull`

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs [hunk 14]
```diff
@@ -365,6 +384,88 @@ public async Task Redacts_HTTP_headers()
...
+        }
+
+        if (!string.IsNullOrEmpty(expectedLogs))
+        {
+            string logLines = loggerProvider.GetAsText();
+            logLines.Should().Contain(expectedLogs);
+        }
+    }
+
+    private static string MockAccessToken()
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: Should be a static readonly field.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs [hunk 15]
```diff
@@ -365,6 +384,88 @@ public async Task Redacts_HTTP_headers()
...
+        if (cloudControllerResponse == "timeout")
+        {
+            await Assert.ThrowsAsync<TaskCanceledException>(() => client.SendAsync(httpRequestMessage, TestContext.Current.CancellationToken));
+        }
+        else
+        {
+            HttpResponseMessage response = await client.SendAsync(httpRequestMessage, TestContext.Current.CancellationToken);
+            response.StatusCode.Should().Be(steeltoeStatusCode);
+
+            if (!string.IsNullOrEmpty(errorMessage))
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]:
```suggestion
            if (errorMessage != null)
```

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 12 above)
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: It took me a while to understand why this works. The HTTP mock abuses the application name to register the different responses. It would be clearer to rename `cloudControllerResponse` to `scenario`.

As _every_ test verifies a scenario, the name `CloudControllerScenarioTesting` should be clarified. Suggestion: Returns expected response on permission check.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs [hunk 16]
```diff
@@ -41,8 +43,64 @@ public async Task GetPermissionsTest()
...
+        EndpointPermissions result = await permissionsProvider.ParsePermissionsAsync(response, TestContext.Current.CancellationToken);
+        result.Should().Be(EndpointPermissions.Full);
+    }
+
+    [InlineData("unavailable", HttpStatusCode.ServiceUnavailable, PermissionsProvider.CloudfoundryNotReachableMessage)]
+    [InlineData("not-found", HttpStatusCode.Unauthorized, PermissionsProvider.InvalidTokenMessage)]
+    [InlineData("unauthorized", HttpStatusCode.Unauthorized, PermissionsProvider.InvalidTokenMessage)]
+    [InlineData("forbidden", HttpStatusCode.Forbidden, PermissionsProvider.AccessDeniedMessage)]
+    [InlineData("timeout", HttpStatusCode.ServiceUnavailable, PermissionsProvider.CloudfoundryNotReachableMessage)]
+    [InlineData("exception", HttpStatusCode.InternalServerError, "Exception of type 'System.Net.Http.HttpRequestException' was thrown.")]
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: Can use `typeof().FullName`

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs [hunk 17]
```diff
@@ -41,8 +43,64 @@ public async Task GetPermissionsTest()
...
+    [InlineData("no_sensitive_data", HttpStatusCode.OK, "")]
+    [InlineData("success", HttpStatusCode.OK, "")]
+    [Theory]
+    public async Task CloudControllerScenarioTesting(string cloudControllerResponse, HttpStatusCode steeltoeStatusCode, string? expectedMessage)
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: Same comments about the test name and `cloudControllerResponse` parameter. Additionally, `expectedMessage` should not be nullable -or- tests should pass null instead of "".

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/StartupWithSecurity.cs [hunk 18]
```diff
@@ -22,4 +25,15 @@ public void ConfigureServices(IServiceCollection services)
...
+
+        public HttpClient CreateClient(string name)
+        {
+            return _mockHttpMessageHandler.ToHttpClient();
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/StartupWithSecurity.cs]: It would be cleaner to use `DelegateToMockHttpClientHandler`, see example usage [here](https://github.com/SteeltoeOSS/Steeltoe/blob/main/src/Discovery/test/Eureka.Test/EurekaDiscoveryClientTest.cs#L289) (with HttpClientFactory).

The advantage is that the test doesn't need to know the name of the `HttpClient`, so the constant doesn't need to be public.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 8 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: With that change, these can't be constants and then don't work as inline theory data

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs (hunk 16 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: That results in [CS0182](https://learn.microsoft.com/dotnet/csharp/language-reference/compiler-messages/parameter-argument-mismatch?#arguments-for-attributes), do you have a workaround that is worth the effort to implement?

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 15 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: N/A after other changes

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/StartupWithSecurity.cs (hunk 13 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/StartupWithSecurity.cs]: N/A after other changes

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 11 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: These names are attempting to indicate the source of the interaction that triggered the log message

eg: A Cloud Foundry "Forbidden" message triggered this log vs the later case where the Steeltoe middleware evaluation determined that the Http message from the test should be forbidden. I think using "Provider" here would be confusing. I considered trying to indicate Cloud Controller somehow, but I think "CF" is accurate enough for differentiating between logs due to Steeltoe code vs external interactions

File: src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs (hunk 7 above)
Comment (TimHess) [reply src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs]: Just letting it throw would take us out of alignment with Spring and in some cases could make it harder or at least slower to track down exactly what went wrong.

I'd prefer to catch everything we can and provide the maximum (safe to share) level of detail that's available, including catching those timeouts so that we can clearly and concisely say that it's a problem with the underlying platform infrastructure (Cloud Controller) and is definitely not from the app.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 11 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: I didn't spend time looking into this next bit, but there were also some cases where we _could_ assert that more than one log entry was written. 

I tried several variations of including line breaks but decided it likely wasn't worth pursuing since it would likely either complicate the inline data (what does it look like to optionally have more than one log entry parameter) or require more of these fields. If you have thoughts we could try something, but I'm of the opinion that what we have is enough and there would be diminishing returns on any additional work put in there (if any benefit at all).

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/StartupWithSecurity.cs (hunk 18 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/StartupWithSecurity.cs]: The constant is in an internal class, so it already isn't _actually_ public... Regardless, this change does not have any impact on the accessor b/c it's still needed in `EndpointServiceCollectionExtensions.cs`, but it'll now use `DelegateToMockHttpClientHandler`

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 8 above)
Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: Ah, that's unfortunate.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs (hunk 16 above)
Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: No, unfortunately.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 15 above)
Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: Why make this so complicated? Now we have two vars that indirectly depend on each other, in such a way that the compiler can't infer nullability anymore, and so we need extra null conditionals. Instead, we should just keep the `if (errorMessage != null)` check, then declare the `jsonErrorValue` inside the `if` block, because it's not used anywhere else.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 12 above)
Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: The change to `InvokeAsyncReturnsExpected` doesn't look right to me. There is no actual `InvokeAsync` call anywhere in the test method body, because it's not a unit test, but an integration test. Therefore, I think we should express the functional scenario being covered in the test name.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs [hunk 19]
```diff
@@ -417,40 +388,55 @@ public async Task CloudControllerScenarioTesting(string cloudControllerResponse,
...
         using IWebHost host = builder.Build();
+        host.Services.GetRequiredService<HttpClientHandlerFactory>().Using(CloudControllerPermissionsMock.GetHttpMessageHandler());
         await host.StartAsync(TestContext.Current.CancellationToken);
 
         using HttpClient client = host.GetTestClient();
-        var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, new Uri("http://localhost/cloudfoundryapplication"));
-        httpRequestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", MockAccessToken());
+        var hypermediaRequestMessage = new HttpRequestMessage(HttpMethod.Get, new Uri("http://localhost/cloudfoundryapplication"));
+        hypermediaRequestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", MockAccessToken);
+        var fullPermissionRequestMessage = new HttpRequestMessage(HttpMethod.Get, new Uri("http://localhost/cloudfoundryapplication/info"));
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: Should this be named `infoRequestMessage`, given we also have `hypermediaRequestMessage`?

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs [hunk 20]
```diff
@@ -15,34 +17,92 @@ namespace Steeltoe.Management.Endpoint.Test.Actuators.CloudFoundry;
...
+        unauthorized.Code.Should().Be(HttpStatusCode.Unauthorized);
+        unauthorized.Message.Should().Be(PermissionsProvider.Messages.AuthorizationHeaderInvalid);
     }
 
-    [Fact]
-    public async Task GetPermissionsTest()
+    [InlineData(false, true, EndpointPermissions.Restricted)]
+    [InlineData(true, true, EndpointPermissions.Full)]
+    [Theory]
+    public async Task ParsePermissionsAsyncReturnsExpected(bool readSensitive, bool readBasic, EndpointPermissions expectedPermissions)
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]:
```suggestion
    public async Task ParsePermissionsResponseAsyncReturnsExpected(bool readSensitive, bool readBasic, EndpointPermissions expectedPermissions)
```

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs [hunk 21]
```diff
@@ -28,40 +29,43 @@ public async Task EmptyTokenIsUnauthorized()
...
     {
         PermissionsProvider permissionsProvider = GetPermissionsProvider();
         var response = new HttpResponseMessage(HttpStatusCode.OK);
 
-        var permissions = new Dictionary<string, object>
+        var permissionsJson = new Dictionary<string, bool>
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: But this is a dictionary, not JSON. I find the change confusing.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 19 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: Probably not, the reason for two requests isn't really to test hypermedia and info... It's because we want one request that needs to be authenticated and one that needs to be authenticated and authorized. I'll rename again to indicate AuthN vs AuthZ

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs (hunk 21 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: The name of this thing should not matter at all; I'm just going to inline it.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs [hunk 22]
```diff
@@ -101,13 +103,13 @@ public async Task InvokeAsync(HttpContext context)
...
+        if (request.Headers.TryGetValue(HeaderNames.Authorization, out StringValues authorizationHeaderValue))
         {
-            string header = headerValue.ToString();
+            string authorizationValue = authorizationHeaderValue.ToString();
 
-            if (header.StartsWith(PermissionsProvider.BearerHeaderNamePrefix, StringComparison.OrdinalIgnoreCase))
+            if (authorizationValue.StartsWith(BearerTokenPrefix, StringComparison.OrdinalIgnoreCase))
             {
-                return header[PermissionsProvider.BearerHeaderNamePrefix.Length..];
+                return authorizationValue[BearerTokenPrefix.Length..];
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs:112]: In method `CloudFoundrySecurityMiddleware.ReturnErrorAsync`:

image

Is this a bug? The comment seems to contradict the code.

File: src/Common/src/Common/Extensions/ExceptionExtensions.cs [hunk 23]
```diff
@@ -59,4 +59,21 @@ public static bool IsCancellation(this Exception? exception)
...
         return false;
     }
+
+    /// <summary>
+    /// Determines whether the thrown exception results from an HTTP request timeout.
+    /// </summary>
+    /// <param name="exception">
+    /// The caught exception to inspect.
+    /// </param>
+    public static bool IsTimeout(this Exception? exception)
```
Comment (bart-vmware) [inline src/Common/src/Common/Extensions/ExceptionExtensions.cs]: This doesn't look right; I would expect such a method to also return `true` when the incoming exception is a `TimeoutException`. Either rename to `IsHttpClientTimeout`, or adapt the code so it becomes generally usable.

Should validate other places in the codebase where `TimeoutException` appears.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs [hunk 24]
```diff
@@ -353,18 +325,88 @@ public async Task Redacts_HTTP_headers()
...
 
         _ = await httpClient.SendAsync(requestMessage, TestContext.Current.CancellationToken);
 
         string logMessages = string.Join(System.Environment.NewLine, capturingLoggerProvider.GetAll());
         logMessages.Should().Contain("Authorization: *");
     }
 
+    [ClassData(typeof(CloudFoundrySecurityMiddlewareTestScenarios))]
+    [Theory]
+    public async Task IntegrationTestReturnsExpected(string scenario, HttpStatusCode? steeltoeStatusCode, string? errorMessage, string[] expectedLogs,
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: In case of a timeout, _two_ messages are logged at Error level. There should be only one at that level:

image

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs [hunk 25]
```diff
@@ -15,34 +17,97 @@ namespace Steeltoe.Management.Endpoint.Test.Actuators.CloudFoundry;
...
+        EndpointPermissions result = await permissionsProvider.ParsePermissionsResponseAsync(cloudControllerResponse, TestContext.Current.CancellationToken);
+        result.Should().Be(expectedPermissions);
+    }
+
+    [InlineData("unavailable", HttpStatusCode.ServiceUnavailable, PermissionsProvider.Messages.CloudFoundryNotReachable)]
+    [InlineData("not-found", HttpStatusCode.Unauthorized, PermissionsProvider.Messages.InvalidToken)]
+    [InlineData("unauthorized", HttpStatusCode.Unauthorized, PermissionsProvider.Messages.InvalidToken)]
+    [InlineData("forbidden", HttpStatusCode.Forbidden, PermissionsProvider.Messages.AccessDenied)]
+    [InlineData("timeout", HttpStatusCode.ServiceUnavailable, PermissionsProvider.Messages.CloudFoundryTimeout)]
+    [InlineData("exception", null, "Exception of type 'System.Net.Http.HttpRequestException' was thrown.")]
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: According to the docs at https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=net-9.0:

> [HttpRequestException](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httprequestexception?view=net-9.0)
The request failed due to an issue getting a valid HTTP response, such as network connectivity failure, DNS failure, server certificate validation error, or invalid server response. On .NET 8 and later versions, the reason is indicated by [HttpRequestError](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httprequestexception.httprequesterror?view=net-9.0#system-net-http-httprequestexception-httprequesterror)

I would expect a `HttpStatusCode.ServiceUnavailable` here. Should also log the `HttpRequestError`, which indicates the reason for the failure.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTestScenarios.cs [hunk 26]
```diff
@@ -0,0 +1,102 @@
...
+// See the LICENSE file in the project root for more information.
+
+using System.Net;
+using Messages = Steeltoe.Management.Endpoint.Actuators.CloudFoundry.PermissionsProvider.Messages;
+
+namespace Steeltoe.Management.Endpoint.Test.Actuators.CloudFoundry;
+
+internal sealed class CloudFoundrySecurityMiddlewareTestScenarios : TheoryData<string, HttpStatusCode?, string?, string[], bool>
+{
+    private const string CFForbiddenLog =
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTestScenarios.cs]: I still think CF is too generic, because it's all about Cloud Foundry. It's not CF producing these log entries; it's our code that's doing so. Can you rename them to indicate what produces them?

And `typeof` can now be used, because they no longer need to be constants.

Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTestScenarios.cs]: Does this name work fine for you? `_permissionsCheckForbiddenLog` 

I don't care if we want to change these names later, it doesn't seem like it's worth spending much time on IMO

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 12 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: Now called `IntegrationTestReturnsExpected`

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs (hunk 17 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: Does this one look ok now?

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTestScenarios.cs (hunk 26 above)
Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTestScenarios.cs]: Why not just `ProviderForbiddenLog`, so it matches with `MiddlewareForbiddenLog`?

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 12 above)
Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: That's similarly vague. Suggestion: Returns expected response on permission check.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs (hunk 22 above)
Comment (TimHess) [reply src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs:112]: The code says "If we should `UseStatusCodeFromResponse` or the error code is less than 500, we should use the status code from the response". The comment is saying "Hi friend, that's nice that you think you don't want to see a 403, but we're going to show it to you anyway because you'd be super confused if we return 200" -- `UseStatusCodeFromResponse` is for IIS/HWC compatibility reasons (and the built-in server error pages that break our ability to return a response body)

File: src/Common/src/Common/Extensions/ExceptionExtensions.cs (hunk 23 above)
Comment (TimHess) [reply src/Common/src/Common/Extensions/ExceptionExtensions.cs]: Yeah, that thought crossed my mind, but I didn't spend much time on it since it's all internal... Do you have a preference for making this generic vs specific?

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTestScenarios.cs (hunk 26 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTestScenarios.cs]: `typeof` requires changing from `const` to `readonly` and thus changes the casing/underscore conventions... this is what I have pending locally:
```csharp
private const string ExceptionLogStart = "FAIL Microsoft.AspNetCore.Server.Kestrel: Connection id";
private const string ExceptionLogEnd = ": An unhandled exception was thrown by the application.";

private const string SuccessLog =
    "INFO System.Net.Http.HttpClient.CloudFoundrySecurity.ClientHandler: Sending HTTP request GET https://example.api.com/v2/apps/success/permissions";

private readonly string _permissionsCheckForbiddenLog =
    $"INFO {typeof(PermissionsProvider)}: Cloud Foundry returned status: Forbidden while obtaining permissions from: https://example.api.com/v2/apps/forbidden/permissions";

private readonly string _permissionsCheckUnauthorizedLog =
    $"INFO {typeof(PermissionsProvider)}: Cloud Foundry returned status: Unauthorized while obtaining permissions from: https://example.api.com/v2/apps/unauthorized/permissions";

private readonly string _permissionsCheckNotFoundLog =
    $"INFO {typeof(PermissionsProvider)}: Cloud Foundry returned status: NotFound while obtaining permissions from: https://example.api.com/v2/apps/not-found/permissions";

private readonly string _permissionsCheckTimeoutLog =
    $"FAIL {typeof(PermissionsProvider)}: Cloud Foundry request timed out while obtaining permissions from: https://example.api.com/v2/apps/timeout/permissions";

private readonly string _middlewareForbiddenLog =
    $"FAIL {typeof(CloudFoundrySecurityMiddleware)}: Actuator Security Error: Forbidden - {Messages.AccessDenied}";

private readonly string _middlewareTimeoutLog =
    $"FAIL{typeof(CloudFoundrySecurityMiddleware)}: Actuator Security Error: ServiceUnavailable - {Messages.CloudFoundryTimeout}";

private readonly string _middlewareUnauthorizedLog =
    $"FAIL {typeof(CloudFoundrySecurityMiddleware)}: Actuator Security Error: Unauthorized - {Messages.InvalidToken}";

private readonly string _middlewareUnavailableLog =
    $"FAIL {typeof(CloudFoundrySecurityMiddleware)}: Actuator Security Error: ServiceUnavailable - {Messages.CloudFoundryNotReachable}";
 ```

File: src/Common/src/Common/Extensions/ExceptionExtensions.cs (hunk 23 above)
Comment (bart-vmware) [reply src/Common/src/Common/Extensions/ExceptionExtensions.cs]: I'm fine making it specific, we don't have other places in the codebase where it matters.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTestScenarios.cs (hunk 26 above)
Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTestScenarios.cs]: Looks good.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs (hunk 22 above)
Comment (bart-vmware) [reply src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs:112]: Can you clarify the comment in code, and link to the related issue?

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs (hunk 17 above)
Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: Should align the name with the other conversation.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs (hunk 24 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: Oh right... I had a change pending in the middleware but scrapped it at some point. How about I just make the permissions provider a warning?

Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudFoundrySecurityMiddlewareTest.cs]: We should never produce duplicate logs when something is misbehaving. Operators tend to aggregate the number of errors and warnings to assess the stability of systems.

If we must log both, one should be at Info level max, but we may as well remove the deepest one, as it doesn't provide additional information to users.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs (hunk 25 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: The PermissionsProvider does not catch anything other than `TimeoutException` anymore... are you suggesting to catch, log and rethrow?

Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/Actuators/CloudFoundry/PermissionsProviderTest.cs]: No! Log or throw, never both -- https://rolf-engelhard.de/2013/04/logging-anti-patterns-part-ii/#:~:text=Log%20and%20Throw&text=Never%20do%20both%20at%20a,might%20log%20that%20exception%20too.

Catch `HttpRequestException`, then convert it into a returned message/status code pair (like most other ones). Log the exception at error level. If not provided already, include `HttpRequestError` in the log message.

File: src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudControllerPermissionsMock.cs [hunk 27]
```diff
@@ -0,0 +1,42 @@
...
+        httpClientHandler.Mock.When(HttpMethod.Get, "https://example.api.com/v2/apps/unauthorized/permissions")
+            .Respond(HttpStatusCode.Unauthorized, "application/json", "{}");
+
+        httpClientHandler.Mock.When(HttpMethod.Get, "https://example.api.com/v2/apps/forbidden/permissions")
+            .Respond(HttpStatusCode.Forbidden, "application/json", "{}");
+
+        httpClientHandler.Mock.When(HttpMethod.Get, "https://example.api.com/v2/apps/timeout/permissions")
+            .Throw(new OperationCanceledException(null, new TimeoutException()));
+
+        httpClientHandler.Mock.When(HttpMethod.Get, "https://example.api.com/v2/apps/exception/permissions").Throw(new HttpRequestException());
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/Actuators/CloudFoundry/CloudControllerPermissionsMock.cs]: Should throw, for example, `new HttpRequestException(HttpRequestError.NameResolutionError)`, so we have something meaningful to assert on.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs [hunk 28]
```diff
@@ -63,13 +65,13 @@ public async Task InvokeAsync(HttpContext context)
                 _logger.LogCritical(
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs]: Please change `LogCritical` to `LogError` here, because the system recovers from this error.

From https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=net-9.0-pp#fields:

> Critical: Logs that describe an unrecoverable application or system crash, or a catastrophic failure that requires immediate attention.

**Review by bart-vmware — APPROVED** [review]
LGTM
