### PR TITLE
Fix S4059: Property names should not match get methods

### LINKED ISSUE #950: Address S4059: Property names should not match get methods
Address existing violations of [S4059: Property names should not match get methods](https://rules.sonarsource.com/csharp/RSPEC-4059) in the codebase and set severity to `Warning` in `Steeltoe.Debug.ruleset` and `Steeltoe.Release.ruleset`.

To find existing violations, enable the rule (see above) and rebuild `src/Steeltoe.All.sln` to make them appear in the Output window.

To address the violations, choose from the following on a case-by-case basis:
- Fix the violation by changing the code to not violate the rule
- Suppress the violation in code using `#pragma warning disable/restore`, preceded by a justification comment if not obvious

### PR DESCRIPTION
**Pull request by bart-vmware**
## Description

Renamed methods to avoid clashes with property names. I'm open to suggestions for better names.

Fixes #950

## Quality checklist

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [x] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [ ] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

File: src/Integration/src/RabbitMQ/Outbound/AbstractRabbitOutboundEndpoint.cs [hunk 1]
```diff
@@ -207,7 +207,7 @@ protected virtual void DoStop()
     {
     }
 
-    protected virtual IMessageChannel GetConfirmAckChannel()
+    protected virtual IMessageChannel GetResolvedConfirmAckChannel()
```
Comment (TimHess) [inline src/Integration/src/RabbitMQ/Outbound/AbstractRabbitOutboundEndpoint.cs:210]: @dtillman does the new name of this method look ok to you?

**Review by dtillman — DISMISSED** [review]
LGTM

**Review by TimHess — APPROVED** [review]
