### PR TITLE
HeapDump & Pipeline enhancements

### LINKED ISSUE #585: Heap Dump actuator via App Manager on TAS (linux container) does not work
When deploying and following the instructions for the CF management sample.  Trying to create a heap dump fails (it downloads an empty dmp file).  The debug logs show the Operation failed.  Seems due to permissions.  

This needs to be verified and if it is an issue with TAS, it will need to be resolved, or at least provide a way to allow a user to have this functionality.

### PR DESCRIPTION
**Pull request by TimHess**
- update DiagnosticsClient
- use the same heap dumper for Linux and .NET 5 on Windows
- support setting heap dump type
- Heap dump is disabled by default with Linux + TAS (related to but does not fix #585)
- update Sonar, react new results with a fix and overrides

### CODE REVIEW

File: src/Management/src/EndpointBase/HeapDump/HeapDumper.cs [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+// See the LICENSE file in the project root for more information.
+
+using Microsoft.Diagnostics.NETCore.Client;
+using Microsoft.Extensions.Logging;
+using System;
+using System.Diagnostics;
+
+namespace Steeltoe.Management.Endpoint.HeapDump
+{
+    public class HeapDumper : IHeapDumper
```
Comment (TimHess) [inline src/Management/src/EndpointBase/HeapDump/HeapDumper.cs:12]: This is `LinuxHeapDumper` but renamed and observing the new HeapDumpType option

File: src/Common/src/Common/Util/MethodInvoker.cs [hunk 2]
```diff
@@ -168,7 +166,9 @@ protected virtual MethodInfo FindMatchingMethod()
                 throw new InvalidOperationException("No target class set");
             }
 
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Common/src/Common/Util/MethodInvoker.cs:169]: Thoughts on this rule and resolving vs disabling?

File: src/Management/test/EndpointCore.Test/HeapDump/EndpointMiddlewareTest.cs [hunk 3]
```diff
@@ -50,10 +51,13 @@ public async void HandleHeapDumpRequestAsync_ReturnsExpected()
                 var logger1 = loggerFactory.CreateLogger<WindowsHeapDumper>();
                 var logger2 = loggerFactory.CreateLogger<HeapDumpEndpoint>();
                 var logger3 = loggerFactory.CreateLogger<HeapDumpEndpointMiddleware>();
-                var logger4 = loggerFactory.CreateLogger<LinuxHeapDumper>();
+                var logger4 = loggerFactory.CreateLogger<HeapDumper>();
 
-                var obs = Platform.IsWindows ? (IHeapDumper)new WindowsHeapDumper(opts, logger: logger1)
-                                : Platform.IsLinux ? (IHeapDumper)new LinuxHeapDumper(opts, logger: logger4)
+                // WindowsHeapDumper should be used with .NET Core 3.1 on Windows. HeapDumper should be used with Linux and .NET 5 on Windows. , O
```
Comment (TimHess) [inline src/Management/test/EndpointCore.Test/HeapDump/EndpointMiddlewareTest.cs:56]:
```suggestion
                // WindowsHeapDumper should be used with .NET Core 3.1 on Windows. HeapDumper should be used with Linux and .NET 5 on Windows
```

File: src/Management/src/EndpointBase/HeapDump/HeapDumpEndpointOptions.cs [hunk 4]
```diff
@@ -24,5 +25,10 @@ public HeapDumpEndpointOptions(IConfiguration config)
                 Id = "heapdump";
             }
         }
+
+        public string HeapDumpType { get; set; }
+
+        // Default to disabled on Linux + Cloud Foundry until PTRACE is allowed
+        public override bool DefaultEnabled { get; } = !Platform.IsCloudFoundry || !Platform.IsLinux;
```
Comment (TimHess) [inline src/Management/src/EndpointBase/HeapDump/HeapDumpEndpointOptions.cs:32]: This will change the default experience, but heap dump on CF + Linux can be re-enabled by using `management:endpoints:heapdump:enabled`

File: src/Management/src/EndpointBase/HeapDump/HeapDumper.cs (hunk 1 above)
Comment (TimHess) [reply src/Management/src/EndpointBase/HeapDump/HeapDumper.cs:12]: Note that there is no support for changing dump type via parameter, only app configuration

File: src/Common/src/Common/Util/MethodInvoker.cs (hunk 2 above)
Comment (dtillman) [reply src/Common/src/Common/Util/MethodInvoker.cs:169]: Disable globally ... when writing framework code we will at times need to implement code that reflects on and invokes private, internal, protected, etc, methods, fields, properties, ...

File: sharedproject.props [hunk 5]
```diff
@@ -19,7 +19,7 @@
     <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
     <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
     <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
-    <NoWarn>SA1101;SA1124;S1128;SA1201;SA1309;SA1310;SA1314;SA1401;SA1402;SA1413;SA1600;SA1629;SA1652;1591;S1854</NoWarn>
+    <NoWarn>SA1101;SA1124;S1128;SA1201;SA1309;SA1310;SA1314;SA1401;SA1402;SA1413;SA1600;SA1629;SA1652;1591;S1854;S4792</NoWarn>
```
Comment (TimHess) [inline sharedproject.props:22]:
```suggestion
    <NoWarn>SA1101;SA1124;S1128;SA1201;SA1309;SA1310;SA1314;SA1401;SA1402;SA1413;SA1600;SA1629;SA1652;1591;S1854;S4792;S3011;</NoWarn>
```

File: src/Common/src/Common/Util/MethodInvoker.cs (hunk 2 above)
Comment (TimHess) [inline src/Common/src/Common/Util/MethodInvoker.cs:169]:
```suggestion
```

File: src/Common/src/Common/Util/MethodInvoker.cs [hunk 6]
```diff
@@ -168,7 +166,9 @@ protected virtual MethodInfo FindMatchingMethod()
...
             MethodInfo[] candidates = targetClass.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance);
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Common/src/Common/Util/MethodInvoker.cs:171]:
```suggestion
```

File: src/Integration/src/IntegrationBase/Extensions/IntegrationServicesExtensions.cs [hunk 7]
```diff
@@ -176,7 +176,9 @@ public static IServiceCollection AddServiceActivators(this IServiceCollection se
             var targetMethods = AttributeUtils.FindMethodsWithAttribute(
                 targetClass,
                 typeof(ServiceActivatorAttribute),
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Integration/src/IntegrationBase/Extensions/IntegrationServicesExtensions.cs:179]:
```suggestion
```

File: src/Integration/src/IntegrationBase/Extensions/IntegrationServicesExtensions.cs [hunk 8]
```diff
@@ -176,7 +176,9 @@ public static IServiceCollection AddServiceActivators(this IServiceCollection se
...
                 BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Integration/src/IntegrationBase/Extensions/IntegrationServicesExtensions.cs:181]:
```suggestion
```

File: src/Integration/src/IntegrationBase/Handler/MethodInvokingMessageProcessor.cs [hunk 9]
```diff
@@ -107,7 +107,9 @@ private static MethodInfo FindAnnotatedMethod(object target, Type attribute)
             var results = AttributeUtils.FindMethodsWithAttribute(
                 target.GetType(),
                 attribute,
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Integration/src/IntegrationBase/Handler/MethodInvokingMessageProcessor.cs:110]:
```suggestion
```

File: src/Integration/src/IntegrationBase/Handler/MethodInvokingMessageProcessor.cs [hunk 10]
```diff
@@ -107,7 +107,9 @@ private static MethodInfo FindAnnotatedMethod(object target, Type attribute)
...
                 BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Integration/src/IntegrationBase/Handler/MethodInvokingMessageProcessor.cs:112]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Handler/Invocation/AbstractMethodMessageHandler.cs [hunk 11]
```diff
@@ -233,7 +233,9 @@ protected void DetectHandlerMethods(object handler)
             if (handlerType != null)
             {
                 var results = new Dictionary<MethodInfo, T>();
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Handler/Invocation/AbstractMethodMessageHandler.cs:236]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Handler/Invocation/AbstractMethodMessageHandler.cs [hunk 12]
```diff
@@ -233,7 +233,9 @@ protected void DetectHandlerMethods(object handler)
...
                 var methods = handlerType.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance);
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Handler/Invocation/AbstractMethodMessageHandler.cs:238]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Message.cs [hunk 13]
```diff
@@ -41,7 +41,9 @@ public static IMessage Create(object payload, Type messageType = null)
 
             return (IMessage)Activator.CreateInstance(
                 typeToCreate,
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Message.cs:44]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Message.cs [hunk 14]
```diff
@@ -41,7 +41,9 @@ public static IMessage Create(object payload, Type messageType = null)
...
                 BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance,
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Message.cs:46]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Message.cs [hunk 15]
```diff
@@ -55,7 +57,9 @@ public static IMessage Create(object payload, IMessageHeaders headers, Type mess
 
             return (IMessage)Activator.CreateInstance(
                   typeToCreate,
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Message.cs:60]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Message.cs [hunk 16]
```diff
@@ -55,7 +57,9 @@ public static IMessage Create(object payload, IMessageHeaders headers, Type mess
...
                   BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance,
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Message.cs:62]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Message.cs [hunk 17]
```diff
@@ -69,7 +73,9 @@ public static IMessage Create(object payload, IDictionary<string, object> header
 
             return (IMessage)Activator.CreateInstance(
                   typeToCreate,
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Message.cs:76]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Message.cs [hunk 18]
```diff
@@ -69,7 +73,9 @@ public static IMessage Create(object payload, IDictionary<string, object> header
...
                   BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance,
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Message.cs:78]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Support/MessageBuilder.cs [hunk 19]
```diff
@@ -22,7 +22,9 @@ public static AbstractMessageBuilder FromMessage(IMessage message, Type payloadT
 
             return (AbstractMessageBuilder)Activator.CreateInstance(
                   typeToCreate,
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Support/MessageBuilder.cs:25]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Support/MessageBuilder.cs [hunk 20]
```diff
@@ -22,7 +22,9 @@ public static AbstractMessageBuilder FromMessage(IMessage message, Type payloadT
...
                   BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance,
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Support/MessageBuilder.cs:27]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Support/MessageBuilder.cs [hunk 21]
```diff
@@ -41,7 +43,9 @@ public static AbstractMessageBuilder WithPayload(object payload, Type payloadTyp
 
             return (AbstractMessageBuilder)Activator.CreateInstance(
                   typeToCreate,
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Support/MessageBuilder.cs:46]:
```suggestion
```

File: src/Messaging/src/MessagingBase/Support/MessageBuilder.cs [hunk 22]
```diff
@@ -41,7 +43,9 @@ public static AbstractMessageBuilder WithPayload(object payload, Type payloadTyp
...
                   BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance,
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/MessagingBase/Support/MessageBuilder.cs:48]:
```suggestion
```

File: src/Messaging/src/RabbitMQ/Support/RabbitMessageBuilder.cs [hunk 23]
```diff
@@ -25,7 +25,9 @@ public static AbstractMessageBuilder FromMessage(IMessage message, Type payloadT
 
             return (AbstractMessageBuilder)Activator.CreateInstance(
                   typeToCreate,
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/RabbitMQ/Support/RabbitMessageBuilder.cs:28]:
```suggestion
```

File: src/Messaging/src/RabbitMQ/Support/RabbitMessageBuilder.cs [hunk 24]
```diff
@@ -25,7 +25,9 @@ public static AbstractMessageBuilder FromMessage(IMessage message, Type payloadT
...
                   BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance,
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/RabbitMQ/Support/RabbitMessageBuilder.cs:30]:
```suggestion
```

File: src/Messaging/src/RabbitMQ/Support/RabbitMessageBuilder.cs [hunk 25]
```diff
@@ -44,7 +46,9 @@ public static AbstractMessageBuilder WithPayload(object payload, Type payloadTyp
 
             return (AbstractMessageBuilder)Activator.CreateInstance(
                   typeToCreate,
+#pragma warning disable S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/RabbitMQ/Support/RabbitMessageBuilder.cs:49]:
```suggestion
```

File: src/Messaging/src/RabbitMQ/Support/RabbitMessageBuilder.cs [hunk 26]
```diff
@@ -44,7 +46,9 @@ public static AbstractMessageBuilder WithPayload(object payload, Type payloadTyp
...
                   BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance,
+#pragma warning restore S3011 // Reflection should not be used to increase accessibility of classes, methods, or fields
```
Comment (TimHess) [inline src/Messaging/src/RabbitMQ/Support/RabbitMessageBuilder.cs:51]:
```suggestion
```

File: src/Common/src/Common/Util/MethodInvoker.cs (hunk 2 above)
Comment (TimHess) [reply src/Common/src/Common/Util/MethodInvoker.cs]: Thanks Dave!

File: src/Management/src/EndpointCore/HeapDump/EndpointServiceCollectionExtensions.cs [hunk 27]
```diff
@@ -42,13 +42,13 @@ public static void AddHeapDumpActuator(this IServiceCollection services, IConfig
                 services.AddActuatorManagementOptions(config);
                 services.AddHeapDumpActuatorServices(config);
 
-                if (Platform.IsWindows)
+                if (RuntimeInformation.FrameworkDescription.StartsWith(".NET Core", StringComparison.InvariantCultureIgnoreCase) && Platform.IsWindows)
```
Comment (jkonicki) [inline src/Management/src/EndpointCore/HeapDump/EndpointServiceCollectionExtensions.cs:45]: So, only use WindowsHeapDumper when it is .NET Core and on Windows? Otherwise use HeapDumper for all other cases?

Comment (jkonicki) [reply src/Management/src/EndpointCore/HeapDump/EndpointServiceCollectionExtensions.cs:45]: Maybe add a comment here to explain the different scenarios you are handling.

File: src/Management/src/EndpointBase/HeapDump/HeapDumpEndpointOptions.cs (hunk 4 above)
Comment (jkonicki) [reply src/Management/src/EndpointBase/HeapDump/HeapDumpEndpointOptions.cs:32]: What about when it is not CF and running on linux (outside of CF)?  It should be enabled then, right?

File: src/Management/src/EndpointCore/HeapDump/EndpointServiceCollectionExtensions.cs (hunk 27 above)
Comment (TimHess) [reply src/Management/src/EndpointCore/HeapDump/EndpointServiceCollectionExtensions.cs:45]: Yes

**Review by hananiel — DISMISSED** [review]
LGTM

File: src/Management/src/EndpointBase/HeapDump/HeapDumpEndpointOptions.cs (hunk 4 above)
Comment (TimHess) [reply src/Management/src/EndpointBase/HeapDump/HeapDumpEndpointOptions.cs:32]: Yes, it will be enabled any time it's not running on Cloud Foundry or if it's not running on Linux.

Comment (TimHess) [reply src/Management/src/EndpointBase/HeapDump/HeapDumpEndpointOptions.cs:32]: Would `!(Platform.IsCloudFoundry && Platform.IsLinux);` be easier to understand?

Comment (jkonicki) [reply src/Management/src/EndpointBase/HeapDump/HeapDumpEndpointOptions.cs:32]: Ahh..  I read through it too quickly.  I like the updated code for readability.

Comment (hananiel) [reply src/Management/src/EndpointBase/HeapDump/HeapDumpEndpointOptions.cs:32]: Yes - that is easier to reason about.
