### PR TITLE
don't mask unauthorized as server error, set a claims id if user has …

### LINKED ISSUE #1441: Potential bug with health details not showing for "WhenAuthorized" in CF
The `WhenAuthorized` setting for the health actuator does not appear to be compatible with the Cloud Foundry security middleware.

While remote debugging to identify why details were missing, a request that should have been authenticated by my user token did not appear authenticated when it hit my breakpoint in `HealthEndpointMiddleware`

### LINKED ISSUE #1442: Incorrect error response for expired token
Sending a request to an actuator endpoint with an expired token currently returns HTTP 503 with the following response body:
```json
{
  "security_error": "Cloud controller not reachable"
}
```

But the following log entry is also written:
```
 Cloud Foundry returned status: Unauthorized while obtaining permissions from: https://{api.systemdomain}/v2/apps/{appguid}/permissions
```

### PR DESCRIPTION
**Pull request by TimHess**
# Description

This PR removes masking of HTTP403 as HTTP503 and sets a user identity if the JWT has some level of app permissions
also removes ability to trace-log all (unredacted) request headers

Fixes #1441, Fixes #1442

## Quality checklist

- [ ] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [ ] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [ ] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

File: src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs [hunk 1]
```diff
@@ -76,7 +76,7 @@ public async Task<SecurityResult> GetPermissionsAsync(string accessToken, Cancel
                 _logger.LogInformation("Cloud Foundry returned status: {HttpStatus} while obtaining permissions from: {PermissionsUri}", response.StatusCode,
                     checkPermissionsUri);
 
-                return response.StatusCode == HttpStatusCode.Forbidden
+                return response.StatusCode is HttpStatusCode.Forbidden or HttpStatusCode.Unauthorized
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs:79]: I still find it odd that we return `HttpStatusCode.ServiceUnavailable` (which is a retryable error) when _any other_ error occurs. For example, HTTP 400 for an incorrect response body, or even 404. But at least this improves the current situation.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs [hunk 2]
```diff
@@ -156,7 +169,7 @@ internal Task<SecurityResult> GetPermissionsAsync(HttpContext context)
 
     private async Task ReturnErrorAsync(HttpContext context, SecurityResult error)
     {
-        LogError(context, error);
+        _logger.LogError("Actuator Security Error: {Code} - {Message}", error.Code, error.Message);
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs:172]: Would it be helpful to at least list the header names?

**Review by bart-vmware — APPROVED** [review]
Left some comments, but feel free to resolve and merge.

**Comment by bart-vmware** [comment]
Oh, I forgot to mention updating the documentation:

- `EndpointOptions.RequiredPermissions`
  > Gets or sets the permissions required to access this endpoint, ~when running on Cloud Foundry~. Default value: Restricted.
- `EndpointPermissions`
  > Represents the level of permissions required to access an endpoint, ~when running on Cloud Foundry~.

In the documentation repo, all actuator endpoints have this description (in the config table) that should be adapted as well:
> Permissions required to access the endpoint, when running on Cloud Foundry.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs (hunk 2 above)
Comment (TimHess) [reply src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs:172]: I think the logging of headers was added before there was a robust middleware available from Microsoft to handle it... I think I'd rather suggest using that to diagnose problems than bundling any form of it here

File: src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs (hunk 1 above)
Comment (TimHess) [reply src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs:79]: Yeah, it's odd, and I either never knew or don't remember the why for some of it, aside from knowledge we were "just making things work" for Apps Manager or IIS/HWC

**Comment by TimHess** [comment]
> Oh, I forgot to mention updating the documentation:
> 
> * `EndpointOptions.RequiredPermissions`
>   > Gets or sets the permissions required to access this endpoint, ~when running on Cloud Foundry~. Default value: Restricted.
> * `EndpointPermissions`
>   > Represents the level of permissions required to access an endpoint, ~when running on Cloud Foundry~.
> 
> In the documentation repo, all actuator endpoints have this description (in the config table) that should be adapted as well:
> 
> > Permissions required to access the endpoint, ~when running on Cloud Foundry~.

The documentation might still be correct here because there is a [translation from a CF permission to `EndpointPermissions`](https://github.com/SteeltoeOSS/Steeltoe/blob/main/src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs#L110) and we don't provide a generic `PermissionsProvider` or guidance on creating your own

File: src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs (hunk 2 above)
Comment (bart-vmware) [reply src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs:172]: The Microsoft middleware handles ASP.NET header logging, but this is about an external call using `HttpClient`.

**Review by bart-vmware — CHANGES_REQUESTED** [review]
Unapproving to further discuss.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs (hunk 2 above)
Comment (bart-vmware) [reply src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs:172]: See also https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/9.0/redact-headers.

File: src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs (hunk 1 above)
Comment (TimHess) [reply src/Management/src/Endpoint/Actuators/CloudFoundry/PermissionsProvider.cs:79]: Logged a follow-up https://github.com/SteeltoeOSS/Steeltoe/issues/1446

File: src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs (hunk 2 above)
Comment (TimHess) [reply src/Management/src/Endpoint/Actuators/CloudFoundry/CloudFoundrySecurityMiddleware.cs:172]: The built-in trace logging is there not matter what we do, so Steeltoe logging was definitely excessive. I've added a call to `RedactLoggedHeaders` and specified Authorization so that the token is not logged

File: src/Management/src/Endpoint/Actuators/CloudFoundry/EndpointServiceCollectionExtensions.cs [hunk 3]
```diff
@@ -62,7 +62,10 @@ private static void ConfigureHttpClient(IServiceCollection services)
         services.TryAddSingleton<HttpClientHandlerFactory>();
         services.TryAddSingleton<ValidateCertificatesHttpClientHandlerConfigurer<CloudFoundryEndpointOptions>>();
 
-        IHttpClientBuilder httpClientBuilder = services.AddHttpClient(PermissionsProvider.HttpClientName);
+        IHttpClientBuilder httpClientBuilder = services.AddHttpClient(PermissionsProvider.HttpClientName).RedactLoggedHeaders(new List<string>
+        {
+            "Authorization"
+        });
```
Comment (bart-vmware) [inline src/Management/src/Endpoint/Actuators/CloudFoundry/EndpointServiceCollectionExtensions.cs:68]:
```suggestion
        IHttpClientBuilder httpClientBuilder = services.AddHttpClient(PermissionsProvider.HttpClientName).RedactLoggedHeaders(["Authorization"]);
```

**Review by bart-vmware — APPROVED** [review]
