### PR TITLE
Log exception in lieu of throwing, when SBA server is not available

### LINKED ISSUE #861: Unhandled exception when Spring Boot Admin not running
## Describe the bug
Application startup with Spring Boot Admin offline generates unhandled exception:

2022-06-01T20:06:17.3268550Z [START] Encountered error during running of app: System.Net.Http.HttpRequestException: Connection refused (localhost:8080)
 ---> System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Steeltoe.Management.Endpoint.SpringBootAdminClient.SpringBootAdminClientHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

## Steps to reproduce 
1.  Add configuration for Spring Boot Admin client (spring:boot:admin:client:url set to "http://localhost:8080")
2. Add code for setting up the client:  services.AddSpringBootAdminClient()
3. Ensure that SBA is NOT running at the configured URL
4. Start the application

## Expected behavior
An error should be logged after catching the httpClient exception in SpringBootAdminClientHostedService.StartAsync() as is done when the client returns a 400 or 500 status.  Application should not terminate, as this makes SBA a critical dependency.

## Environment (please complete the following information):
 - Steeltoe Version [e.g. 3.2.0]
 - Platform: [Docker] 
 - OS: Reproduced on Linux and Mac OSX (Windows not tried)
 - .NET Version [.NET 6] 

## Additional context or links
Works fine if SBA is running at specified URL or admin client not initialized.

### PR DESCRIPTION
**Pull request by hananiel**
## Description

Log exception in lieu of throwing, when SBA server is not available

Fixes #861 

## Quality checklist

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [x] You've updated unit and/or integration tests for your change, where applicable.
- [x] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [x] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

**Comment by TimHess** [comment]
We'll need to backport to `release/3.2` in another PR for inclusion in 3.2.1

**Comment by TimHess** [comment]
> > @hananiel the stacktrace in the linked issue includes `Steeltoe.Management.Endpoint.SpringBootAdminClient.SpringBootAdminClientHostedService.StartAsync`, so this probably won't fix it? I think this is the old code that was replaced by what's in the issue
> 
> I changed in both places - this extension method doesnt result in app crashing but the hostedservice does. I figured it cannot hurt to fix both.

Yep, you did. Juggling too much at once and I was only looking at the sonar report

File: src/Management/src/EndpointBase/SpringBootAdminClient/SpringBootAdminClientHostedService.cs [hunk 1]
```diff
@@ -50,14 +50,29 @@ public async Task StartAsync(CancellationToken cancellationToken)
...
+            result = await _httpClient.PostAsJsonAsync($"{_options.Url}/instances", app, cancellationToken: cancellationToken);
+        }
+        catch (HttpRequestException ex)
+        {
+            _logger.LogError(ex, "Error connecting to SpringBootAdmin: {Message}", ex.Message);
+        }
+        catch (InvalidOperationException ex)
+        {
+            _logger.LogError(ex, "Error connecting to SpringBootAdmin: {Message}", ex.Message);
+        }
```
[the remark this answers is not in the document]
Comment (bart-vmware) [reply src/Management/src/EndpointBase/SpringBootAdminClient/SpringBootAdminClientHostedService.cs:66]: I think it needs to catch `JsonException` as well.

File: src/Management/src/EndpointCore/SpringBootAdminClient/SpringBootAdminApplicationBuilderExtensions.cs [hunk 2]
```diff
@@ -64,14 +64,24 @@ public static void RegisterWithSpringBootAdmin(this IApplicationBuilder builder,
...
+            HttpResponseMessage result = null;
+            string exceptionMessage = null;
+            try
+            {
+                result = httpClient.PostAsJsonAsync($"{options.Url}/instances", app).GetAwaiter().GetResult();
+            }
+            catch (HttpRequestException ex)
+            {
+                exceptionMessage = ex.Message;
+            }
```
Comment (bart-vmware) [inline src/Management/src/EndpointCore/SpringBootAdminClient/SpringBootAdminApplicationBuilderExtensions.cs:76]: Same comment as earlier applies here. Is `InvalidOperationException` intentionally left out?

File: src/Management/src/EndpointCore/SpringBootAdminClient/SpringBootAdminApplicationBuilderExtensions.cs [hunk 3]
```diff
@@ -64,14 +64,24 @@ public static void RegisterWithSpringBootAdmin(this IApplicationBuilder builder,
...
+
+            if (result is { IsSuccessStatusCode: true })
             {
                 RegistrationResult = result.Content.ReadFromJsonAsync<RegistrationResult>().GetAwaiter().GetResult();
             }
             else
             {
-                logger.LogError($"Error registering with SpringBootAdmin {result}");
+                logger?.LogError("Error registering with SpringBootAdmin: {result}.", result?.ToString() ?? exceptionMessage);
```
Comment (bart-vmware) [inline src/Management/src/EndpointCore/SpringBootAdminClient/SpringBootAdminApplicationBuilderExtensions.cs:84]: Please update accordingly to include the response body.

**Review by bart-vmware — DISMISSED** [review]

**Comment by hananiel** [comment]
I reverted the suggestions to catch individual exceptions, because I was just looking for HttpClient.PostAsync, but we are using PostJsonAsync whose [docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions.postasjsonasync?view=net-6.0) don't list individual exceptions. So this may change in the future? I am not sure this is worth the hassle.

File: src/Management/src/EndpointCore/SpringBootAdminClient/SpringBootAdminApplicationBuilderExtensions.cs [hunk 4]
```diff
@@ -21,7 +21,7 @@ namespace Steeltoe.Management.Endpoint.SpringBootAdminClient;
 [Obsolete("This extension will be removed in a future release, please use SpringBootAdminClientHostedService instead")]
```
Comment (TimHess) [inline src/Management/src/EndpointCore/SpringBootAdminClient/SpringBootAdminApplicationBuilderExtensions.cs:21]: I think we're going to remove this class from 4.0 soon, we could do it now, especially since there's no code coverage on it and sonar is complaining about it already

File: src/Management/src/EndpointBase/SpringBootAdminClient/SpringBootAdminClientHostedService.cs [hunk 5]
```diff
@@ -50,14 +50,25 @@ public async Task StartAsync(CancellationToken cancellationToken)
...
         _httpClient.Timeout = TimeSpan.FromMilliseconds(_options.ConnectionTimeoutMS);
-        var result = await _httpClient.PostAsJsonAsync($"{_options.Url}/instances", app);
-        if (result.IsSuccessStatusCode)
+
+        HttpResponseMessage result = null;
+        try
+        {
+            result = await _httpClient.PostAsJsonAsync($"{_options.Url}/instances", app, cancellationToken: cancellationToken);
+        }
+        catch (Exception exception)
```
Comment (TimHess) [inline src/Management/src/EndpointBase/SpringBootAdminClient/SpringBootAdminClientHostedService.cs:59]: Might be worth adding a comment that the generic `Exception` is being caught because ____ reason (I think the reasoning was that it does not matter what the exception is and we should log and continue because this is a non-essential operation) as this will show up at some point with Sonar rules

File: src/Management/src/EndpointCore/SpringBootAdminClient/SpringBootAdminApplicationBuilderExtensions.cs (hunk 4 above)
Comment (TimHess) [reply src/Management/src/EndpointCore/SpringBootAdminClient/SpringBootAdminApplicationBuilderExtensions.cs:21]: Same comment as above regarding catching `Exception` applies

**Review by TimHess — APPROVED** [review]
It's OK for now, but I think we'll be back in here to remove the obsolete code and address the general exception catching relatively soon

File: src/Management/src/EndpointBase/SpringBootAdminClient/SpringBootAdminClientHostedService.cs (hunk 5 above)
Comment (hananiel) [reply src/Management/src/EndpointBase/SpringBootAdminClient/SpringBootAdminClientHostedService.cs:59]: I cannot imagine following that rule consistently across the code base. The better thing is to probably fix the sonar rules.
