### PR TITLE
Fix Loggers, Metrics and Hypermedia when Manangement:Endpoint:Path is…

### LINKED ISSUE #467: POST to loggers actuator fails if the base management path is /
## Describe the bug
When posting to the loggers endpoint when using the dynamic logger to change the log level, the request fails with a 400 bad request if the management endpoints path is `/`. 

## Steps to reproduce 
1. Create a simple AspNet Core app and add Steeltoe Dynamic logging and Management Endpoints.
2. Configure the management endpoints:

```
  "Management": {
    "Endpoints": {
      "Path": "/",
      "Actuator": {
        "Exposure": {
          "Include": [ "info", "health", "loggers" ]
        }
      }
    }
  }
```
3. Attempt to change the level:  POST https://localhost:5000/loggers/Microsoft

## Expected behavior
The request to return a 200 OK and the level should be changed.

## Environment (please complete the following information):
 - Platform: Local
 - OS: Windows 10
 - .NET Version: Core 3.1
 - Steeltoe Version 3.0 (also fails in 2.x line)

### PR DESCRIPTION
**Pull request by hananiel**
… set to / 
resolves #467

### CODE REVIEW

File: src/Management/src/EndpointBase/Hypermedia/HypermediaService.cs [hunk 1]
```diff
@@ -49,7 +49,8 @@ public Links Invoke(string baseUrl)
                 {
                     if (!string.IsNullOrEmpty(opt.Id) && !links._links.ContainsKey(opt.Id))
                     {
-                        links._links.Add(opt.Id, new Link(baseUrl + "/" + opt.Path));
+                        var linkPath = $"{baseUrl.TrimEnd('/')}/{opt.Path}";
```
Comment (TimHess) [inline src/Management/src/EndpointBase/Hypermedia/HypermediaService.cs:52]:
```suggestion
                        var linkPath = $"{baseUrl}/{opt.Path}".Replace("//", "/");
```
For consistency with the other two changes

**Review by TimHess — APPROVED** [review]

File: src/Management/src/EndpointBase/Hypermedia/HypermediaService.cs (hunk 1 above)
Comment (TimHess) [reply src/Management/src/EndpointBase/Hypermedia/HypermediaService.cs:52]: ^ won't work b/c baseUrl is expected to include `://`

Comment (hananiel) [reply src/Management/src/EndpointBase/Hypermedia/HypermediaService.cs:52]: `baseUrl` has Http(s?):// in it, so this change won't work here.  In the other place,  it seemed more efficient to do that since no replace occurs if `//` is not found.
