### PR TITLE
Sonar various

### LINKED ISSUE #912: Address S1067: Expressions should not be too complex
Address existing violations of [S1067: Expressions should not be too complex](https://rules.sonarsource.com/csharp/RSPEC-1067) in the codebase and set severity to `Warning` in `Steeltoe.Debug.ruleset` and `Steeltoe.Release.ruleset`.

To find existing violations, enable the rule (see above) and rebuild `src/Steeltoe.All.sln` to make them appear in the Output window.

To address the violations, choose from the following on a case-by-case basis:
- Fix the violation by changing the code to not violate the rule
  - Most are easy to fix by comparing against a frozen dictionary or extract method
- Suppress the violation in code using `#pragma warning disable/restore`, preceded by a justification comment if not obvious

### LINKED ISSUE #926: Address S2292: Trivial properties should be auto-implemented
Address existing violations of [S2292: Trivial properties should be auto-implemented](https://rules.sonarsource.com/csharp/RSPEC-2292) in the codebase and set severity to `Warning` in `Steeltoe.Debug.ruleset` and `Steeltoe.Release.ruleset`.

To find existing violations, enable the rule (see above) and rebuild `src/Steeltoe.All.sln` to make them appear in the Output window.

To address the violations, choose from the following on a case-by-case basis:
- Fix the violation by changing the code to not violate the rule
- Suppress the violation in code using `#pragma warning disable/restore`, preceded by a justification comment if not obvious

### LINKED ISSUE #927: Address S2302: "nameof" should be used
Address existing violations of [S2302: "nameof" should be used](https://rules.sonarsource.com/csharp/RSPEC-2302) in the codebase and set severity to `Warning` in `Steeltoe.Debug.ruleset` and `Steeltoe.Release.ruleset`.

To find existing violations, enable the rule (see above) and rebuild `src/Steeltoe.All.sln` to make them appear in the Output window.

To address the violations, choose from the following on a case-by-case basis:
- Fix the violation by changing the code to not violate the rule
- ~Suppress the violation in code using `#pragma warning disable/restore`, preceded by a justification comment if not obvious~

Note: This rule results in many false positives, so consider to use Rider/Resharper analysis instead to fix existing problems and leave this rule disabled.

Related to #940.

### LINKED ISSUE #940: Address S3928: Parameter names used into ArgumentException constructors should match an existing one
Address existing violations of [S3928: Parameter names used into ArgumentException constructors should match an existing one](https://rules.sonarsource.com/csharp/RSPEC-3928) in the codebase and set severity to `Warning` in `Steeltoe.Debug.ruleset` and `Steeltoe.Release.ruleset`.

To find existing violations, enable the rule (see above) and rebuild `src/Steeltoe.All.sln` to make them appear in the Output window.

To address the violations, choose from the following on a case-by-case basis:
- Fix the violation by changing the code to not violate the rule
- ~Suppress the violation in code using `#pragma warning disable/restore`, preceded by a justification comment if not obvious~

Related to #927.

### LINKED ISSUE #948: Address S4039: Interface methods should be callable by derived types
Address existing violations of [S4039: Interface methods should be callable by derived types](https://rules.sonarsource.com/csharp/RSPEC-4039) in the codebase and set severity to `Warning` in `Steeltoe.Debug.ruleset` and `Steeltoe.Release.ruleset`.

To find existing violations, enable the rule (see above) and rebuild `src/Steeltoe.All.sln` to make them appear in the Output window.

To address the violations (currently one), choose from the following on a case-by-case basis:
- Fix the violation by changing the code to not violate the rule
- Suppress the violation in code using `#pragma warning disable/restore`, preceded by a justification comment if not obvious

### PR DESCRIPTION
**Pull request by bart-vmware**
## Description

Addressed Sonar rules:
- Fixed S1067: Expressions should not be too complex
- Fixed S2292: Trivial properties should be auto-implemented
- Reviewed S2302: "nameof" should be used
  - Fixed a small set of violations, but many false positives remain, so keeping this rule turned off
- Fixed S3928: Parameter names used into `ArgumentException` constructors should match an existing one
- Fixed S4039: Interface methods should be callable by derived types

Other:
- Introduced argument guards and converted existing usages of Argument*Exception
- Renamed parameters of type `System.Type` to contain 'Type' suffix
- Use structured log messages, remove unneeded `ToString()` calls, ensure exceptions are propagated and fix parameter order
- Remove line break between property get/set and event add/remove
  - StyleCop used to require this, while the Resharper formatter has a bug that fails to remove them
- Rename files to match type name, remove unneeded Resharper exclusion, cleanup `AssemblyInfo.cs` files

Fixes #912
Fixes #926
Fixes #927
Fixes #940
Fixes #948

## Quality checklist

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [x] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [ ] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

File: src/Discovery/src/Eureka/EurekaPostConfigurer.cs [hunk 1]
```diff
@@ -191,6 +182,37 @@ public static void UpdateConfiguration(IConfiguration config, EurekaServiceInfo
...
+        {
+            return;
+        }
+
+        if (!clientOptions.ShouldRegisterWithEureka && !clientOptions.ShouldFetchRegistry)
+        {
+            return;
+        }
+
+        throw new InvalidOperationException(
```
Comment (TimHess) [inline src/Discovery/src/Eureka/EurekaPostConfigurer.cs:212]: Possibly outside the scope of this PR, but if we can log instead of throwing it _might_ be preferable https://github.com/SteeltoeOSS/Steeltoe/issues/829

File: src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs [hunk 2]
```diff
@@ -46,10 +46,22 @@ static bool Query(Type t)
...
-                    t.Name.StartsWith("HeapDump");
+                bool isThreadDump = type.Name.StartsWith("ThreadDump", StringComparison.Ordinal);
+                bool isHeapDump = type.Name.StartsWith("HeapDump", StringComparison.Ordinal);
+
+                if (!(isThreadDump || isHeapDump))
+                {
+                    return true;
+                }
+
+                if (isThreadDump && Platform.IsWindows)
```
Comment (TimHess) [inline src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs:64]: I think this is incorrect... ThreadDump should work on any platform since #822 (and some cleanup in #848). Also looks like the docs never got updated to indicate this changed

File: src/CircuitBreaker/src/Abstractions/Properties/AssemblyInfo.cs [hunk 3]
```diff
@@ -4,28 +4,4 @@
...
-// Version information for an assembly consists of the following four values:
-//
-//      Major Version
-//      Minor Version
-//      Build Number
-//      Revision
-//
-// [assembly: AssemblyVersion("1.0.0.0")]
-// [assembly: AssemblyFileVersion("1.0.0.0")]
 [assembly: InternalsVisibleTo("Steeltoe.CircuitBreaker.HystrixBase.Test")]
```
[the remark this answers is not in the document]
Comment (bart-vmware) [reply src/CircuitBreaker/src/Abstractions/Properties/AssemblyInfo.cs]: Thanks. I took the suggestion, then realized the entire file should be deleted instead, so I force-pushed that.

File: src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs (hunk 2 above)
Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs:64]: Glad you're bringing this up. The result looked odd to me, so I double-checked to ensure the refactoring didn't change the outcome. What should it be instead? And which documentation are you referring to?

File: src/Discovery/src/Eureka/EurekaPostConfigurer.cs (hunk 1 above)
Comment (bart-vmware) [reply src/Discovery/src/Eureka/EurekaPostConfigurer.cs:212]: The linked issue is about `ConsulPostConfigurer` (called from `ValidateConsulOptions()`), while this comment is on `EurekaPostConfigurer` (called from `UpdateConfiguration()`). Does the same concern apply here?

For both, we could add `bool AreOptionsValid()`, which enables callers to check upfront. Then the callers can be expanded with a `bool throwOnError` parameter. These are just suggestions without me fully understanding the context, so my thinking is this is probably better first discussed in the linked issue, followed by a separate PR (and possibly backported).

File: src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs (hunk 2 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs:64]: I guess this line would just be `if (isThreadDump)`, but that makes the whole method look a bit weird since SupportedOnPlatform is basically always true now

File: src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs [hunk 4]
```diff
@@ -46,10 +46,22 @@ static bool Query(Type t)
...
+                {
+                    return true;
+                }
```
Comment (bart-vmware) [inline src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs:67]:
```suggestion
                return isThreadDump || isHeapDump;
```

Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs:67]: Is that what it should be?

Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs:67]: Or remove `SupportedOnPlatform` entirely?

File: src/Discovery/src/Eureka/EurekaPostConfigurer.cs (hunk 1 above)
Comment (TimHess) [reply src/Discovery/src/Eureka/EurekaPostConfigurer.cs:212]: Yes the same concern applies. yeah, let's postpone changes for now

File: src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs (hunk 4 above)
Comment (TimHess) [reply src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs:67]: I think we can delete this whole thing, the result should always be `true`

File: src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs [hunk 5]
```diff
@@ -46,10 +46,22 @@ static bool Query(Type t)
...
+
+                return isHeapDump;
             }
 
             List<Type> types = Assembly.Load("Steeltoe.Management.Endpoint").GetTypes().Where(Query).Where(SupportedOnPlatform).ToList();
```
Comment (TimHess) [inline src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs:72]:
```suggestion
            List<Type> types = Assembly.Load("Steeltoe.Management.Endpoint").GetTypes().Where(Query).ToList();
```

Comment (bart-vmware) [reply src/Management/test/Endpoint.Test/ActuatorRouteBuilderExtensionsTest.cs]: Thanks, I've already pushed a commit to address this (and keep the formatter happy).

**Review by TimHess — APPROVED** [review]
LGTM
