### PR TITLE
Fix issues with refresh polling

### LINKED ISSUE #1217: Setting a non-zero PollingInterval with FailFast enabled on the Config Server Configuration Provider can cause the application to crash
## Describe the bug
When FailFast is enabled along with a non-zero PollingInterval, the application will crash if there is an exception thrown when polling the config server to refresh the configuration (e.g. due to a timeout). The console output looks like the following:

```
fail: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]
      Config Server exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 6 seconds elapsing.
       ---> System.TimeoutException: The operation was canceled.
       ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
       ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
       ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, Cance
llationToken originalCancellationToken)
         --- End of inner exception stack trace ---
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsC
ts)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, Cance
llationToken originalCancellationToken)
         at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.RemoteLoadAsync(String requestUri), path: http%3A%2F%2Flocalhost%3A8763%2Ffoo%2FProduction
warn: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]
      Could not locate PropertySource: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 6 seconds elapsing.
       ---> System.TimeoutException: The operation was canceled.
       ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
       ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
       ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSockeUnhandled exception. tAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, Cance
llationToken originalCancellationToken)
         --- End of inner exception stack trace ---
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsC
ts)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposSteeltoe.Extensions.Configuration.ConfigServer.ConfigSe
rverException: Could not locate PropertySource, fail fast property is set, failing
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 6 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, Cancellatio
nToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)   
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, Cancellatio
nToken originalCancellationToken)
   at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.RemoteLoadAsync(String requestUri)
   at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.DoLoad(Boolean updateDictionary)
   --- End of inner exception stack trace ---
   at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.DoLoad(Boolean updateDictionary)
   at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.<OnSettingsChanged>b__27_1(Object _)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
eCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.RemoteLoadAsync(String requestUri)
         at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.DoLoad(Boolean updateDictionary)

Process finished with exit code -532,462,766.

```

## Steps to reproduce 
1. Start with the "Simple" configuration sample here:
https://github.com/SteeltoeOSS/Samples/tree/main/Configuration/src/Simple
2. Change appsettings.json to add the FailFast property under the Spring:Cloud:Config section and set it to true
3. Change appsettings.json to add the PollingInterval property under the Spring:Cloud:Config section and set it to "00:00:15"
4. Start up a test config server and wait for it to finish starting.
5. Start up the "Simple" configuration sample application and wait for it to finish starting.
6. Stop the test config server.
7. Wait until the next polling interval (up to 15 seconds) for the sample application to crash.

## Expected behavior
The refresh polling should not crash the application. If it is unsuccessful in loading the configuration it should probably just log a warning.

## Environment (please complete the following information):
 - Steeltoe Version: 3.2.5
 - Platform: N/A 
 - OS: Windows
 - .NET Version: 6.0

## Additional context or links
This seems due to an unhandled exception being thrown within the [callback of a System.Threading.Timer](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs#L163), which crashes the application. When FailFast is true, [an exception may be thrown within the Load method](https://github.com/SteeltoeOSS/Steeltoe/blob/release/3.2/src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs#L364). I think the timer callback should wrap the call to the Load method in a try/catch and log any exception.

### LINKED ISSUE #1218: Disabling the config server client doesn't disable refresh polling
## Describe the bug
When the Enabled property is set to false with a non-zero PollingInterval, the refresh polling is not disabled as expected. There are still requests made to the config server every polling interval. If the config server is unreachable, the console output looks like the following every interval:
```
fail: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]                                                   
      Config Server exception: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:8763)                          
       ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.                                                        
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)                                                 
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)                                                 
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, Cance
llationToken originalCancellationToken)
         at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.RemoteLoadAsync(String requestUri), path: http%3A%2F%2Flocalhost%3A8763%2Ffoo%2FProduction
warn: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider[0]
      Could not locate PropertySource: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:8763)
       ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, Cance
llationToken originalCancellationToken)
         at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.RemoteLoadAsync(String requestUri)
         at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.DoLoad(Boolean updateDictionary)

```  

## Steps to reproduce 
1. Start with the "Simple" configuration sample here:
https://github.com/SteeltoeOSS/Samples/tree/main/Configuration/src/Simple
2. Change appsettings.json to add the Enabled property under the Spring:Cloud:Config section and set it to false
3. Change appsettings.json to add the PollingInterval property under the Spring:Cloud:Config section and set it to "00:00:15"
4. Make sure the config server at the configured Uri is stopped
5. Start the "Simple" configuration sample
6. See the exception in the console output every 15 seconds

## Expected behavior
Refresh polling should also be disabled when the Enabled property is set to false

## Environment (please complete the following information):
 - Steeltoe Version: 3.2.5
 - Platform: N/A 
 - OS: Windows
 - .NET Version: 6.0

### PR DESCRIPTION
**Pull request by douggish**
## Description

If polling was enabled along with the fail fast setting, it was possible for unhandled exceptions to be thrown within a Timer callback, which crashed the application. Also the polling was not disabled when the Enabled configuration was set to false. This PR wraps the load in the Timer callback within a try/catch. It also only starts polling if Enabled is true.

Fixes #1217
Fixes #1218

## Quality checklist

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [x] You've updated unit and/or integration tests for your change, where applicable.
- [x] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [x] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

File: src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs [hunk 1]
```diff
@@ -154,17 +160,35 @@ private void OnSettingsChanged()
...
+        try
         {
-            _refreshTimer = new Timer(_ => DoLoad(), null, TimeSpan.Zero, _settings.PollingInterval);
+            DoLoad();
         }
-        else if (existingPollingInterval != _settings.PollingInterval)
+        catch (Exception e)
         {
-            _refreshTimer.Change(TimeSpan.Zero, _settings.PollingInterval);
+            _logger.LogWarning("Could not reload configuration during polling" + e);
```
Comment (TimHess) [inline src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs:191]:
```suggestion
            _logger.LogWarning(e, "Could not reload configuration during polling");
```

**Review by TimHess — DISMISSED** [review]
LGTM, just a nit on the log message

**Comment by TimHess** [comment]
Thanks for filing the issues and opening the PR! We will need to make sure this change gets applied to `main` as well

**Review by TimHess — APPROVED** [review]

File: src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs (hunk 1 above)
Comment (douggish) [reply src/Configuration/src/ConfigServerBase/ConfigServerConfigurationProvider.cs]: OK, sure. I committed the change.

**Comment by douggish** [comment]
> Thanks for filing the issues and opening the PR! We will need to make sure this change gets applied to `main` as well

No problem. We are hoping 3.2.6 will be released fairly soon so that we can continue to use the polling feature without the potential for our app to crash.

**Comment by douggish** [comment]
Hi @TimHess. We are wondering when the 3.2.6 version will be released with this fix. Are you able to give an update on that?

**Comment by TimHess** [comment]
Hi @douggish, Coincidentally, I just kicked off the build to produce the packages. We should be able to ship the fix tomorrow

**Comment by douggish** [comment]
> Hi @douggish, Coincidentally, I just kicked off [the build](https://dev.azure.com/SteeltoeOSS/Steeltoe/_build/results?buildId=20789&view=results) to produce the packages. We should be able to ship the fix tomorrow

OK, that's awesome. Thanks for the quick reply!
