### PR TITLE
Fix actuators when used with UsePathBase

### LINKED ISSUE #1617: hrefs in Hypermedia actuator are wrong if using app.UsePathBase() in version 4.0.0
## Describe the bug
hrefs in Hypermedia actuator are wrong if using app.UsePathBase() in version 4.0.0

## Steps to reproduce
1. Use `app.UsePathBase("base")` in Startup to configure different base path
2. Run app and open `/base/actuator`

## Expected behavior
3. `_links.health.href` should be `/base/actuator/health`, but actually is `/actuator/health`

## Environment (please complete the following information):
 - Steeltoe Version: 4.0.0
 - Platform: Azure Contaner Apps
 - OS: Linux
 - .NET Version: .Net 9.0

## Additional context or links
Was working on Version 3.x.x

### PR DESCRIPTION
**Pull request by bart-vmware**
## Description

Applies `HttpContext.Request.PathBase` when rendering hypermedia links. Logs a warning when middleware is registered multiple times. Removes `PathBase` from the URL being passed to actuator handlers, so that internal checks work properly when `UsePathBase` is used.

Fixes #1617.

- [x] Your code complies with our [Coding Style](https://github.com/SteeltoeOSS/.github/blob/main/contributing-docs/contributing-code-style.md).
- [x] You've updated unit and/or integration tests for your change, where applicable.
- [ ] You've updated documentation for your change, where applicable.
      If your change affects other repositories, such as [Documentation](https://github.com/SteeltoeOSS/Documentation), [Samples](https://github.com/SteeltoeOSS/Samples) and/or [MainSite](https://github.com/SteeltoeOSS/MainSite), add linked PRs here.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.
- [ ] You've added required license files and/or file headers (explaining where the code came from with proper attribution), where code is copied from StackOverflow, a blog, or OSS.

### CODE REVIEW

File: src/Management/src/Endpoint/Actuators/Hypermedia/HypermediaService.cs [hunk 1]
```diff
@@ -68,6 +76,11 @@ public Links Invoke(Uri baseUrl)
         bool skipExposureCheck = PermissionsProvider.IsCloudFoundryRequest(baseUrl.PathAndQuery);
         string? basePath = managementOptions.GetBasePath(baseUrl.AbsolutePath);
 
+        if (_httpContextAccessor.HttpContext?.Request != null)
```
Comment (TimHess) [inline src/Management/src/Endpoint/Actuators/Hypermedia/HypermediaService.cs:79]: I'm guessing there wouldn't be significant impact, but could go deeper and check `PathBase` for null or empty here

File: src/Management/src/Endpoint/ConfigureActuatorsMiddlewareStartupFilter.cs [hunk 2]
```diff
@@ -33,9 +45,30 @@ public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
...
+    private static int? GetMiddlewareCount(IApplicationBuilder app)
+    {
+        FieldInfo? componentsField = app.GetType().GetField("_components", BindingFlags.NonPublic | BindingFlags.Instance);
+        return componentsField?.GetValue(app) is List<Func<RequestDelegate, RequestDelegate>> components ? components.Count(IsMiddleware) : null;
+    }
+
+    private static bool IsMiddleware(Func<RequestDelegate, RequestDelegate> component)
+    {
+        // This type exists so that ASP.NET Core can identify where to inject UseRouting. It is not a real middleware.
+        return component.Target == null || component.Target.ToString() != "Microsoft.AspNetCore.Builder.WebApplicationBuilder+WireSourcePipeline";
```
Comment (TimHess) [inline src/Management/src/Endpoint/ConfigureActuatorsMiddlewareStartupFilter.cs:72]: This seems like it casts a fairly wide net, can/should we only look for `UsePathBaseMiddleware`?

Comment (bart-vmware) [reply src/Management/src/Endpoint/ConfigureActuatorsMiddlewareStartupFilter.cs:72]: Why?

File: src/Management/src/Endpoint/Actuators/Hypermedia/HypermediaService.cs (hunk 1 above)
Comment (bart-vmware) [reply src/Management/src/Endpoint/Actuators/Hypermedia/HypermediaService.cs:79]: I don't understand. `PathString` is a struct.

Comment (TimHess) [reply src/Management/src/Endpoint/Actuators/Hypermedia/HypermediaService.cs:79]: Fair point

File: src/Management/src/Endpoint/ConfigureActuatorsMiddlewareStartupFilter.cs (hunk 2 above)
Comment (TimHess) [reply src/Management/src/Endpoint/ConfigureActuatorsMiddlewareStartupFilter.cs:72]: I was working under the assumption we were only looking for the pathbase, but per our call there could be other middlewares that interfere. Sounds like the detection logic should stay, but we can alter the messaging to make things a little clearer

File: src/Management/src/Endpoint/ConfigureActuatorsMiddlewareStartupFilter.cs [hunk 3]
```diff
@@ -33,9 +45,30 @@ public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
...
 
+            int? beforeMiddlewareCount = GetMiddlewareCount(app);
             next.Invoke(app);
+            int? afterMiddlewareCount = GetMiddlewareCount(app);
+
+            if (beforeMiddlewareCount != afterMiddlewareCount)
+            {
+                _logger.LogWarning(
+                    "Your app adds custom middleware to the pipeline, while actuators were registered to auto-perform middleware setup. This combination is usually undesired. " +
+                    "To correct this, either remove your middleware setup code, or register actuators by setting their configureMiddleware parameter to false.");
```
Comment (TimHess) [inline src/Management/src/Endpoint/ConfigureActuatorsMiddlewareStartupFilter.cs]:
```suggestion
                    "Actuators were registered with automatic middleware setup, and at least one additional middleware was registered afterward. This combination is usually undesired. " +
                    "To remove this warning, either remove the additional middleware registration or set configureMiddleware to false when registering actuators.");
```

File: src/Management/test/Endpoint.Test/Actuators/All/AllActuatorsTest.cs [hunk 4]
```diff
@@ -132,4 +134,24 @@ public async Task Does_not_register_duplicate_services(HostBuilderType hostBuild
...
+        await using WebApplication host = builder.Build();
+
+        host.UseRouting();
+        host.UseActuatorEndpoints();
+
+        await host.StartAsync(TestContext.Current.CancellationToken);
+
+        capturingLoggerProvider.GetAll().Should().Contain($"WARN {typeof(ConfigureActuatorsMiddlewareStartupFilter)}: " +
+            "Your app adds custom middleware to the pipeline, while actuators were registered to auto-perform middleware setup. This combination is usually undesired. " +
+            "To correct this, either remove your middleware setup code, or register actuators by setting their configureMiddleware parameter to false.");
```
Comment (TimHess) [inline src/Management/test/Endpoint.Test/Actuators/All/AllActuatorsTest.cs]:
```suggestion
            "Actuators were registered with automatic middleware setup, and at least one additional middleware was registered afterward. This combination is usually undesired. " +
            "To remove this warning, either remove the additional middleware registration or set configureMiddleware to false when registering actuators.");
```
